version: "3.8"

services:
  db:
    image: mfmathpaint-mariadb
    security_opt:
      - "no-new-privileges"
    cap_drop:
      - ALL
    build:
      context: .
      dockerfile: Dockerfile.mariadb
      secrets:
        - mariadb_user
        - mariadb_password
    networks:
      - "mfmathpaint"
    expose:
      - "3306"

  app:
    image: mfmathpaint-apache
    security_opt:
      - "no-new-privileges"
    cap_drop:
      - ALL
    build:
      context: ../..
      dockerfile: docker/with-secrets/Dockerfile
    environment:
      MARIADB_HOST: db
    networks:
      - "mfmathpaint"
    ports:
      - "80:8080"
    secrets:
      - mariadb_user
      - mariadb_password
networks:
  mfmathpaint:
secrets:
  mariadb_user:
    file: ../secrets/mariadb_user.txt
  mariadb_password:
    file: ../secrets/mariadb_password.txt
