version: "3.8"

services:
  db:
    image: mariadb:10.5
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: yes
      MARIADB_USER: mfmathpaint
      MARIADB_PASSWORD: password
      MARIADB_DATABASE: mfmathpaint
    networks:
      - "mfmathpaint"
    expose:
      - "3306"
  
  app:
    image: mfmathpaint-apache
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      MARIADB_USER: mfmathpaint
      MARIADB_PASSWORD: password
      MARIADB_HOST: db
    networks:
      - "mfmathpaint"
    ports:
      - "80:8080"
networks:
  mfmathpaint:
