version: "3.8"

services:
  db:
    image: mariadb:10.5
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: yes
      MARIADB_USER_FILE: /run/secrets/mariadb_user
      MARIADB_PASSWORD_FILE: /run/secrets/mariadb_password
      MARIADB_DATABASE: mfmathpaint
    networks:
      - "mfmathpaint"
    expose:
      - "3306"
    secrets:
      - mariadb_user
      - mariadb_password

  app:
    image: mfmathpaint-apache
    build:
      context: ../..
      dockerfile: docker/with-secrets/Dockerfile
    environment:
      MARIADB_HOST: db
    networks:
      - "mfmathpaint"
    ports:
      - "80:8080"
    secrets:
      - mariadb_user
      - mariadb_password
networks:
  mfmathpaint:
secrets:
  mariadb_user:
    file: ./mariadb_user.txt
  mariadb_password:
    file: ./mariadb_password.txt
