version: "3.8"

services:
  db:
    image: mariadb:10.5
    security_opt:
      - "no-new-privileges"
    cap_add:
      - SETUID
      - SETGID
    cap_drop:
      - ALL
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: yes
      MARIADB_USER: mfmathpaint
      MARIADB_PASSWORD: password
      MARIADB_DATABASE: mfmathpaint
    networks:
      - "mfmathpaint"
    expose:
      - "3306"
  
  app:
    image: mfmathpaint-apache
    security_opt:
      - "no-new-privileges"
    cap_drop:
      - ALL
    build:
      context: ../..
      dockerfile: docker/simple/Dockerfile
    environment:
      MARIADB_USER: mfmathpaint
      MARIADB_PASSWORD: password
      MARIADB_HOST: db
    networks:
      - "mfmathpaint"
    ports:
      - "80:8080"
networks:
  mfmathpaint:
